### ISSUE TITLE
Question in pkg dependence 

### ISSUE THREAD

**Issue by unl1k3ly** [ALPAC-4/auto_repay#1]
Awesome project !

Thank you so much for doing this.

I did start something in python using anchor and mirror CLI. I wish both had a python SDK for simplicity !!

Anyways, what is the need for `"fs": "0.0.1-security"` ?  in pks dependence ?  Is it really required ? 

https://www.npmjs.com/package/fs

I'm not too familiar with nodejs.

Ty

**Comment by ALPAC-4** [comment]
fs is for reading option.txt

**Comment by unl1k3ly** [comment]
ty!
