### ISSUE TITLE
Get Mnemonic from user input

### ISSUE THREAD

**Issue by Chinoman10** [ALPAC-4/auto_repay#5]
I just spent more than an hour trying to make the script able to run from just `npm start` and if there isn't a `mnemonic` on the `.env`, it'll prompt the user.
Unfortunately, I just couldn't get it to work, possibly because I'm rather new to NodeJS.
I believe someone experienced can handle such an easy feature in just a few minutes.

The idea/reason is simple:
- `.env` isn't very safe, as has already been started;
- giving the seed phrase as a process argument isn't that much better since most users won't know they should put a ` ` (space) before `npm start` so that the phrase isn't recorded on the command line history...
- by checking if the mnemonic is empty, it should prompt the user for it; this way it's not stored anywhere but the machine's memory (RAM), and we could potentially do `process.stdout.write('\033c');` to clear the console (so it's also not visible by scrolling).

**Comment by ALPAC-4** [comment]
Okay let me try it on next update. But isn't it enough that using `npm start seed seed seed ...` ?

**Comment by Chinoman10** [comment]
There are two things you're not considering:

- People who use the program, might leave their computers unattended, or not protect their computer/VPS well enough, so an intruder can read from the console the seed phrase...
- You explicitly say that people shouldn't write on `.env` because it's not safe, right? But having the seed phrase stored on .bash_history is? :)

If it's any good... I tried writing this piece of code:

```js
async function mnemonicCheck() {
    let passphrase = process.env.MNEMONIC != '' ? process.env.MNEMONIC : process.argv[2]
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    // To be used once the function works properly (pauses for user input)
/*    rl.on('SIGINT', () => {
        rl.question('Are you sure you want to exit? ', (answer) => {
          if (answer.match(/^y(es)?$/i)) rl.pause();
        });
    });*/

    while (!(passphrase)) {
        rl.question("What is your wallet passphrase? ", (mnemonic_ans) => {
            passphrase = mnemonic_ans
            rl.close();
            // process.stdout.write('\033c'); // uncomment this if you wish to clear the console after the input, so that the passphrase isn't seen in clear text
            if (!(passphrase)) {
                console.log("Pass-phrase was kept empty. Exiting...")
                process.exit(0);
            }
        })
        
        await sleep (1000) // this shouldn't be needed... but the JS isn't waiting for the user input for some reason...
        // tried with this: https://stackoverflow.com/questions/18193953/waiting-for-user-to-enter-input-in-node-js but didn't work either...
    }
    return passphrase
}

async function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}



async function main(){
    //await mnemonicCheck();
    let option_check = await check_option()
    let UST_check = await check_remain_UST()```

**Comment by Chinoman10** [comment]
I ended up creating a bash script which I use to launch instead of npm.

```bash
#!/bin/bash

echo -n "Seed phrase: "
read -s _seed
echo
npm start "$_seed" | grep -v "node index.js"
```
